services:
  front-end:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0

  back-end:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
